import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const distDir = path.resolve('dist');
const swPath = path.join(distDir, 'sw.js');

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...await walk(full));
    else if (entry.isFile()) files.push(full);
  }
  return files;
}

function asUrl(file) {
  return `./${path.relative(distDir, file).replace(/\\/g, '/')}`;
}

const files = (await walk(distDir))
  .filter((file) => path.resolve(file) !== swPath)
  .sort((a, b) => asUrl(a).localeCompare(asUrl(b)));

const hash = createHash('sha256');
for (const file of files) {
  const info = await stat(file);
  hash.update(asUrl(file));
  hash.update(String(info.size));
  hash.update(await readFile(file));
}

const buildId = hash.digest('hex').slice(0, 12);
const precacheUrls = ['./', ...files.map(asUrl)];

const sw = `// Generated by scripts/generate-sw.mjs. Do not edit dist/sw.js by hand.
const CACHE_PREFIX = 'worldforge-';
const CACHE_NAME = 'worldforge-${buildId}';
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  let url;
  try { url = new URL(request.url); } catch { return; }
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request, './index.html'));
    return;
  }

  event.respondWith(cacheFirst(request));
});

async function networkFirst(request, fallbackUrl) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (isCacheable(response)) await cache.put(request, response.clone());
    return response;
  } catch {
    return (await cache.match(request)) || (await cache.match(fallbackUrl)) || Response.error();
  }
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (isCacheable(response)) await cache.put(request, response.clone());
  return response;
}

function isCacheable(response) {
  return response && response.status === 200 && response.type === 'basic';
}
`;

await writeFile(swPath, sw);
console.log(`Generated service worker ${CACHE_NAME_MESSAGE(buildId)} with ${precacheUrls.length} precache entries.`);

function CACHE_NAME_MESSAGE(id) {
  return `worldforge-${id}`;
}
